In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Food_Delivery_Times.csv')
df.dropna(inplace=True)
print(df.isnull().sum())
print(df.head())

Order_ID                  0
Distance_km               0
Weather                   0
Traffic_Level             0
Time_of_Day               0
Vehicle_Type              0
Preparation_Time_min      0
Courier_Experience_yrs    0
Delivery_Time_min         0
dtype: int64
   Order_ID  Distance_km Weather Traffic_Level Time_of_Day Vehicle_Type  \
0       522         7.93   Windy           Low   Afternoon      Scooter   
1       738        16.42   Clear        Medium     Evening         Bike   
2       741         9.52   Foggy           Low       Night      Scooter   
3       661         7.44   Rainy        Medium   Afternoon      Scooter   
4       412        19.03   Clear           Low     Morning         Bike   

   Preparation_Time_min  Courier_Experience_yrs  Delivery_Time_min  
0                    12                     1.0                 43  
1                    20                     2.0                 84  
2                    28                     1.0                 59  
3       

In [3]:
df=df.drop("Order_ID",axis=1)
df

Distance_km Weather Traffic_Level Time_of_Day Vehicle_Type  \
0           7.93   Windy           Low   Afternoon      Scooter   
1          16.42   Clear        Medium     Evening         Bike   
2           9.52   Foggy           Low       Night      Scooter   
3           7.44   Rainy        Medium   Afternoon      Scooter   
4          19.03   Clear           Low     Morning         Bike   
..           ...     ...           ...         ...          ...   
995         8.50   Clear          High     Evening          Car   
996        16.28   Rainy           Low     Morning      Scooter   
997        15.62   Snowy          High     Evening      Scooter   
998        14.17   Clear           Low   Afternoon         Bike   
999         6.63   Foggy           Low       Night      Scooter   

     Preparation_Time_min  Courier_Experience_yrs  Delivery_Time_min  
0                      12                     1.0                 43  
1                      20                     2.0                 84  
2                      28                     1.0                 59  
3                       5                     1.0                 37  
4                      16                     5.0                 68  
..                    ...                     ...                ...  
995                    13                     3.0                 54  
996                     8                     9.0                 71  
997                    26                     2.0                 81  
998                     8                     0.0                 55  
999                    24                     3.0                 58  

[883 rows x 8 columns]

In [4]:
df=pd.get_dummies(df)
df

Distance_km  Preparation_Time_min  Courier_Experience_yrs  \
0           7.93                    12                     1.0   
1          16.42                    20                     2.0   
2           9.52                    28                     1.0   
3           7.44                     5                     1.0   
4          19.03                    16                     5.0   
..           ...                   ...                     ...   
995         8.50                    13                     3.0   
996        16.28                     8                     9.0   
997        15.62                    26                     2.0   
998        14.17                     8                     0.0   
999         6.63                    24                     3.0   

     Delivery_Time_min  Weather_Clear  Weather_Foggy  Weather_Rainy  \
0                   43          False          False          False   
1                   84           True          False          False   
2                   59          False           True          False   
3                   37          False          False           True   
4                   68           True          False          False   
..                 ...            ...            ...            ...   
995                 54           True          False          False   
996                 71          False          False           True   
997                 81          False          False          False   
998                 55           True          False          False   
999                 58          False           True          False   

     Weather_Snowy  Weather_Windy  Traffic_Level_High  Traffic_Level_Low  \
0            False           True               False               True   
1            False          False               False              False   
2            False          False               False               True   
3            False          False               False              False   
4            False          False               False               True   
..             ...            ...                 ...                ...   
995          False          False                True              False   
996          False          False               False               True   
997           True          False                True              False   
998          False          False               False               True   
999          False          False               False               True   

     Traffic_Level_Medium  Time_of_Day_Afternoon  Time_of_Day_Evening  \
0                   False                   True                False   
1                    True                  False                 True   
2                   False                  False                False   
3                    True                   True                False   
4                   False                  False                False   
..                    ...                    ...                  ...   
995                 False                  False                 True   
996                 False                  False                False   
997                 False                  False                 True   
998                 False                   True                False   
999                 False                  False                False   

     Time_of_Day_Morning  Time_of_Day_Night  Vehicle_Type_Bike  \
0                  False              False              False   
1                  False              False               True   
2                  False               True              False   
3                  False              False              False   
4                   True              False               True   
..                   ...                ...                ...   
995                False              False              False   
996                 True              Fal

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

X_new=df.drop("Delivery_Time_min",axis=1)
Y_new=df["Delivery_Time_min"]
X_train,X_test,Y_train,Y_test=train_test_split(X_new,Y_new,test_size=0.3,random_state=42)

model=LogisticRegression()
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
print("Accuracy Score: ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix: ",confusion_matrix(Y_test,Y_pred))
print("Classification Report: ",classification_report(Y_test,Y_pred))


Accuracy Score:  0.045283018867924525
Confusion Matrix:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:                precision    recall  f1-score   support

           8       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         2
          17       0.50      0.50      0.50         2
          20       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         3
          22       0.00      0.00      0.00         2
          23       0.00      0.00      0.00         1
          24       0.20      1.00      0.33         1
          25       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         2
          27       0.00      0.00      0.00         4
          28       0.00      0.00      0.00         3
          29       0.00      0.00      0.0

c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1

In [7]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
print("Accuracy Score: ",accuracy_score(Y_test,Y_pred))
print("Confusion Matrix: ",confusion_matrix(Y_test,Y_pred))
print("Classification Report: ",classification_report(Y_test,Y_pred))


Accuracy Score:  0.03018867924528302
Confusion Matrix:  [[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:                precision    recall  f1-score   support

           8       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         2
          17       0.00      0.00      0.00         2
          18       0.00      0.00      0.00         0
          19       0.00      0.00      0.00         0
          20       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         3
          22       0.00      0.00      0.00         2
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00

c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{

In [8]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
print("Accuracy Score: ",accuracy_score(Y_test,Y_pred))

Accuracy Score:  0.026415094339622643


In [12]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
print("Accuracy Score: ",model.score(X_test,Y_test))

Accuracy Score:  0.8322833793910046
